insert into posta (postna_st, posta) values (1, 'Strachówka');
insert into posta (postna_st, posta) values (2, 'Ibaan');
insert into posta (postna_st, posta) values (3, 'Maputi');
insert into posta (postna_st, posta) values (4, 'Doibang');
insert into posta (postna_st, posta) values (5, 'Alençon');
insert into posta (postna_st, posta) values (6, 'Lüjiabao');
insert into posta (postna_st, posta) values (7, 'Sanshandao');
insert into posta (postna_st, posta) values (8, 'Jinzhuang');
insert into posta (postna_st, posta) values (9, 'Penanggal');
insert into posta (postna_st, posta) values (10, 'Dabagou');
insert into posta (postna_st, posta) values (11, 'Melenki');
insert into posta (postna_st, posta) values (12, 'Kidangbang');
insert into posta (postna_st, posta) values (13, 'Kamalasai');
insert into posta (postna_st, posta) values (14, 'Santa Magdalena');
insert into posta (postna_st, posta) values (15, 'Paris 18');
insert into posta (postna_st, posta) values (16, 'Miaoling');
insert into posta (postna_st, posta) values (17, 'Pego Longo');
insert into posta (postna_st, posta) values (18, 'Wellington');
insert into posta (postna_st, posta) values (19, 'Collingwood');
insert into posta (postna_st, posta) values (20, 'Lawesigalagala Timur');
insert into posta (postna_st, posta) values (21, 'Bajo');
insert into posta (postna_st, posta) values (22, 'Imġarr');
insert into posta (postna_st, posta) values (23, 'Dongning');
insert into posta (postna_st, posta) values (24, 'Shushi');
insert into posta (postna_st, posta) values (25, 'Muyinga');
insert into posta (postna_st, posta) values (26, 'Zhezqazghan');
insert into posta (postna_st, posta) values (27, 'Kuznechnoye');
insert into posta (postna_st, posta) values (28, 'Novi Karlovci');
insert into posta (postna_st, posta) values (29, 'Xinfang');
insert into posta (postna_st, posta) values (30, 'Villa Consuelo');
insert into posta (postna_st, posta) values (31, 'Wenxi');
insert into posta (postna_st, posta) values (32, 'La Estrella');
insert into posta (postna_st, posta) values (33, 'San Fernando');
insert into posta (postna_st, posta) values (34, 'Ulluaya');
insert into posta (postna_st, posta) values (35, 'Ringinrejo');
insert into posta (postna_st, posta) values (36, 'Imbituva');
insert into posta (postna_st, posta) values (37, 'Dębowiec');
insert into posta (postna_st, posta) values (38, 'Flandes');
insert into posta (postna_st, posta) values (39, 'Nay Pyi Taw');
insert into posta (postna_st, posta) values (40, 'Trzciana');
insert into posta (postna_st, posta) values (41, 'Le Havre');
insert into posta (postna_st, posta) values (42, 'Novorossiysk');
insert into posta (postna_st, posta) values (43, 'Peraía');
insert into posta (postna_st, posta) values (44, 'Lanpelan');
insert into posta (postna_st, posta) values (45, 'Sirājganj');
insert into posta (postna_st, posta) values (46, 'Panikian');
insert into posta (postna_st, posta) values (47, 'Balingasag');
insert into posta (postna_st, posta) values (48, 'Campo Quijano');
insert into posta (postna_st, posta) values (49, 'San Fabian');
insert into posta (postna_st, posta) values (50, 'Gråbo');
insert into posta (postna_st, posta) values (51, 'Zolochiv');
insert into posta (postna_st, posta) values (52, 'Funza');
insert into posta (postna_st, posta) values (53, 'Heqian');
insert into posta (postna_st, posta) values (54, 'Vadstena');
insert into posta (postna_st, posta) values (55, 'Wahang Dua');
insert into posta (postna_st, posta) values (56, 'Petaling Jaya');
insert into posta (postna_st, posta) values (57, 'Pułtusk');
insert into posta (postna_st, posta) values (58, 'Yantan');
insert into posta (postna_st, posta) values (59, 'Głubczyce');
insert into posta (postna_st, posta) values (60, 'Huanggu');
insert into posta (postna_st, posta) values (61, 'Barg-e Matāl');
insert into posta (postna_st, posta) values (62, 'Minador do Negrão');
insert into posta (postna_st, posta) values (63, 'Dushi');
insert into posta (postna_st, posta) values (64, 'Huyuan');
insert into posta (postna_st, posta) values (65, 'Krajan Tanjungrejo');
insert into posta (postna_st, posta) values (66, 'Bucheon-si');
insert into posta (postna_st, posta) values (67, 'Strachówka');
insert into posta (postna_st, posta) values (68, 'Cawayan');
insert into posta (postna_st, posta) values (69, 'Santo Domingo');
insert into posta (postna_st, posta) values (70, 'Rydułtowy');
insert into posta (postna_st, posta) values (71, 'Genova');
insert into posta (postna_st, posta) values (72, 'Pas Pul');
insert into posta (postna_st, posta) values (73, 'Tenggun Dajah');
insert into posta (postna_st, posta) values (74, 'Jiangwang');
insert into posta (postna_st, posta) values (75, 'Dalonghua');
insert into posta (postna_st, posta) values (76, 'Xinmin');
insert into posta (postna_st, posta) values (77, 'Calgary');
insert into posta (postna_st, posta) values (78, 'Baini');
insert into posta (postna_st, posta) values (79, 'Homeyo');
insert into posta (postna_st, posta) values (80, 'Ludvika');
insert into posta (postna_st, posta) values (81, 'Balitai');
insert into posta (postna_st, posta) values (82, 'Łanięta');
insert into posta (postna_st, posta) values (83, 'Charlottenberg');
insert into posta (postna_st, posta) values (84, 'Barbalha');
insert into posta (postna_st, posta) values (85, 'Revelstoke');
insert into posta (postna_st, posta) values (86, 'Sigou');
insert into posta (postna_st, posta) values (87, 'Vanves');
insert into posta (postna_st, posta) values (88, 'Kuttu');
insert into posta (postna_st, posta) values (89, 'Ganquan');
insert into posta (postna_st, posta) values (90, 'Xinbei');
insert into posta (postna_st, posta) values (91, 'Odiongan');
insert into posta (postna_st, posta) values (92, 'San Quintin');
insert into posta (postna_st, posta) values (93, 'Xiadu');
insert into posta (postna_st, posta) values (94, 'Ocucaje');
insert into posta (postna_st, posta) values (95, 'Tangguhang');
insert into posta (postna_st, posta) values (96, 'Liangdong');
insert into posta (postna_st, posta) values (97, 'Duru');
insert into posta (postna_st, posta) values (98, 'Vierzon');
insert into posta (postna_st, posta) values (99, 'Kasba Tadla');
insert into posta (postna_st, posta) values (100, 'Tangtou');
insert into posta (postna_st, posta) values (101, 'Banturkrajan');
insert into posta (postna_st, posta) values (102, 'Kotabumi');
insert into posta (postna_st, posta) values (103, 'Banjar Timbrah');
insert into posta (postna_st, posta) values (104, 'Qingshu');
insert into posta (postna_st, posta) values (105, 'Huatan');
insert into posta (postna_st, posta) values (106, 'São João');
insert into posta (postna_st, posta) values (107, 'Boa Esperança');
insert into posta (postna_st, posta) values (108, 'Örebro');
insert into posta (postna_st, posta) values (109, 'Xibali');
insert into posta (postna_st, posta) values (110, 'Aughrim');
insert into posta (postna_st, posta) values (111, 'Artur Nogueira');
insert into posta (postna_st, posta) values (112, 'Pericik');
insert into posta (postna_st, posta) values (113, 'Pirot');
insert into posta (postna_st, posta) values (114, 'Nanao');
insert into posta (postna_st, posta) values (115, 'Chita');
insert into posta (postna_st, posta) values (116, 'Semënov');
insert into posta (postna_st, posta) values (117, 'Xike');
insert into posta (postna_st, posta) values (118, 'Pirapora do Bom Jesus');
insert into posta (postna_st, posta) values (119, 'Bayamo');
insert into posta (postna_st, posta) values (120, 'Torkanivka');
insert into posta (postna_st, posta) values (121, 'Pindushi');
insert into posta (postna_st, posta) values (122, 'Stockholm');
insert into posta (postna_st, posta) values (123, 'Dibba Al-Fujairah');
insert into posta (postna_st, posta) values (124, 'Niebocko');
insert into posta (postna_st, posta) values (125, 'Guanting');
insert into posta (postna_st, posta) values (126, 'Krasnyy Gulyay');
insert into posta (postna_st, posta) values (127, 'Passo Fundo');
insert into posta (postna_st, posta) values (128, 'Rama');
insert into posta (postna_st, posta) values (129, 'Moutfort');
insert into posta (postna_st, posta) values (130, 'Yihe');
insert into posta (postna_st, posta) values (131, 'Marseille');
insert into posta (postna_st, posta) values (132, 'Palocabildo');
insert into posta (postna_st, posta) values (133, 'Châtellerault');
insert into posta (postna_st, posta) values (134, 'Qiaoxia');
insert into posta (postna_st, posta) values (135, 'Naj‘ Ḩammādī');
insert into posta (postna_st, posta) values (136, 'Qiaotou');
insert into posta (postna_st, posta) values (137, 'Ranao');
insert into posta (postna_st, posta) values (138, 'Neiva');
insert into posta (postna_st, posta) values (139, 'Tartu');
insert into posta (postna_st, posta) values (140, 'Kuala Terengganu');
insert into posta (postna_st, posta) values (141, 'Vannes');
insert into posta (postna_st, posta) values (142, 'Teresita');
insert into posta (postna_st, posta) values (143, 'Cimalati');
insert into posta (postna_st, posta) values (144, 'Batujaran');
insert into posta (postna_st, posta) values (145, 'Huiyi');
insert into posta (postna_st, posta) values (146, 'Sungaibengkal');
insert into posta (postna_st, posta) values (147, 'North Bay');
insert into posta (postna_st, posta) values (148, 'Sogati');
insert into posta (postna_st, posta) values (149, 'Phatthana Nikhom');
insert into posta (postna_st, posta) values (150, 'Nangang');
insert into posta (postna_st, posta) values (151, 'Walagar');
insert into posta (postna_st, posta) values (152, 'Lyubokhna');
insert into posta (postna_st, posta) values (153, 'Kawanoechō');
insert into posta (postna_st, posta) values (154, 'Chishan');
insert into posta (postna_st, posta) values (155, 'Pizhma');
insert into posta (postna_st, posta) values (156, 'Formosa do Rio Preto');
insert into posta (postna_st, posta) values (157, 'Kobarid');
insert into posta (postna_st, posta) values (158, 'Amirabad');
insert into posta (postna_st, posta) values (159, 'Saltsjö-Boo');
insert into posta (postna_st, posta) values (160, 'Strzyżowice');
insert into posta (postna_st, posta) values (161, 'Shaxi');
insert into posta (postna_st, posta) values (162, 'Carmen');
insert into posta (postna_st, posta) values (163, 'Paprotnia');
insert into posta (postna_st, posta) values (164, 'Hujiaying');
insert into posta (postna_st, posta) values (165, 'Chepes');
insert into posta (postna_st, posta) values (166, 'Washington');
insert into posta (postna_st, posta) values (167, 'Ranot');
insert into posta (postna_st, posta) values (168, 'Verkhnyaya Tura');
insert into posta (postna_st, posta) values (169, 'Jalālpur Pīrwāla');
insert into posta (postna_st, posta) values (170, 'Palhoça');
insert into posta (postna_st, posta) values (171, 'Haparanda');
insert into posta (postna_st, posta) values (172, 'Santuario');
insert into posta (postna_st, posta) values (173, 'Yidao');
insert into posta (postna_st, posta) values (174, 'Yuanping');
insert into posta (postna_st, posta) values (175, 'Kediri');
insert into posta (postna_st, posta) values (176, 'Episkopí');
insert into posta (postna_st, posta) values (177, 'Hutag');
insert into posta (postna_st, posta) values (178, 'Hekinan');
insert into posta (postna_st, posta) values (179, 'Tandzut');
insert into posta (postna_st, posta) values (180, 'Kesha');
insert into posta (postna_st, posta) values (181, 'Rantepang');
insert into posta (postna_st, posta) values (182, 'Pojan');
insert into posta (postna_st, posta) values (183, 'Igcocolo');
insert into posta (postna_st, posta) values (184, 'Nacaome');
insert into posta (postna_st, posta) values (185, 'Roldanillo');
insert into posta (postna_st, posta) values (186, 'Lyantonde');
insert into posta (postna_st, posta) values (187, 'Moncada');
insert into posta (postna_st, posta) values (188, 'Hujirt');
insert into posta (postna_st, posta) values (189, 'Panórama');
insert into posta (postna_st, posta) values (190, 'Rungis');
insert into posta (postna_st, posta) values (191, 'Sokol');
insert into posta (postna_st, posta) values (192, 'Funafuti');
insert into posta (postna_st, posta) values (193, 'Venlo');
insert into posta (postna_st, posta) values (194, 'Stěbořice');
insert into posta (postna_st, posta) values (195, 'Měřín');
insert into posta (postna_st, posta) values (196, 'Ngembak');
insert into posta (postna_st, posta) values (197, 'Xinzheng');
insert into posta (postna_st, posta) values (198, 'Kudara-Somon');
insert into posta (postna_st, posta) values (199, 'Xiachengzi');
insert into posta (postna_st, posta) values (200, 'Tawangsari');
insert into posta (postna_st, posta) values (201, 'Newcastle');
insert into posta (postna_st, posta) values (202, 'Daze');
insert into posta (postna_st, posta) values (203, 'Kiryū');
insert into posta (postna_st, posta) values (204, 'Birmingham');
insert into posta (postna_st, posta) values (205, 'La Sebala du Mornag');
insert into posta (postna_st, posta) values (206, 'Bogra');
insert into posta (postna_st, posta) values (207, 'Tân An');
insert into posta (postna_st, posta) values (208, 'Patía');
insert into posta (postna_st, posta) values (209, 'Ghazni');
insert into posta (postna_st, posta) values (210, 'Kista');
insert into posta (postna_st, posta) values (211, 'Piña');
insert into posta (postna_st, posta) values (212, 'Linao');
insert into posta (postna_st, posta) values (213, 'Delareyville');
insert into posta (postna_st, posta) values (214, 'Mingjiu');
insert into posta (postna_st, posta) values (215, 'Bondokodi');
insert into posta (postna_st, posta) values (216, 'Gavião');
insert into posta (postna_st, posta) values (217, 'Yangxunqiao');
insert into posta (postna_st, posta) values (218, 'Libušín');
insert into posta (postna_st, posta) values (219, 'Gandu');
insert into posta (postna_st, posta) values (220, 'Rousínov');
insert into posta (postna_st, posta) values (221, 'Kendung Timur');
insert into posta (postna_st, posta) values (222, 'Storozhnytsya');
insert into posta (postna_st, posta) values (223, 'Pasirlimus');
insert into posta (postna_st, posta) values (224, 'Ágios Vasíleios');
insert into posta (postna_st, posta) values (225, 'Buenos Aires');
insert into posta (postna_st, posta) values (226, 'Manicahan');
insert into posta (postna_st, posta) values (227, 'Faratsiho');
insert into posta (postna_st, posta) values (228, 'Biao');
insert into posta (postna_st, posta) values (229, 'Jiuchi');
insert into posta (postna_st, posta) values (230, 'San Fernando Apure');
insert into posta (postna_st, posta) values (231, 'São José de Ribamar');
insert into posta (postna_st, posta) values (232, 'Purong');
insert into posta (postna_st, posta) values (233, 'Cogon');
insert into posta (postna_st, posta) values (234, 'Donja Mahala');
insert into posta (postna_st, posta) values (235, 'Montecarlo');
insert into posta (postna_st, posta) values (236, 'Ilihan');
insert into posta (postna_st, posta) values (237, 'Banjarsari');
insert into posta (postna_st, posta) values (238, 'Cabalaoangan');
insert into posta (postna_st, posta) values (239, 'Besao');
insert into posta (postna_st, posta) values (240, 'Karangharjo');
insert into posta (postna_st, posta) values (241, 'Safonovo');
insert into posta (postna_st, posta) values (242, 'Regimin');
insert into posta (postna_st, posta) values (243, 'Mathambgwane');
insert into posta (postna_st, posta) values (244, 'Bantog');
insert into posta (postna_st, posta) values (245, 'Přimda');
insert into posta (postna_st, posta) values (246, 'Carhuamayo');
insert into posta (postna_st, posta) values (247, 'Long’anqiao');
insert into posta (postna_st, posta) values (248, 'Puncakwangi');
insert into posta (postna_st, posta) values (249, 'Žulová');
insert into posta (postna_st, posta) values (250, 'Dongfanghong');
insert into posta (postna_st, posta) values (251, 'Purong');
insert into posta (postna_st, posta) values (252, 'Ochobo');
insert into posta (postna_st, posta) values (253, 'Cabannungan Second');
insert into posta (postna_st, posta) values (254, 'Kanash');
insert into posta (postna_st, posta) values (255, 'Hartswater');
insert into posta (postna_st, posta) values (256, 'Costeira do Pirajubae');
insert into posta (postna_st, posta) values (257, 'São Gonçalo do Sapucaí');
insert into posta (postna_st, posta) values (258, 'Hacıhüseynli');
insert into posta (postna_st, posta) values (259, 'Nong Phok');
insert into posta (postna_st, posta) values (260, 'Apeldoorn');
insert into posta (postna_st, posta) values (261, 'Narsaq');
insert into posta (postna_st, posta) values (262, 'Tumbi');
insert into posta (postna_st, posta) values (263, 'Magtaking');
insert into posta (postna_st, posta) values (264, 'Sankt Lorenzen im Mürztal');
insert into posta (postna_st, posta) values (265, 'Mchinji');
insert into posta (postna_st, posta) values (266, 'Menanga');
insert into posta (postna_st, posta) values (267, 'Corrientes');
insert into posta (postna_st, posta) values (268, 'Shuangshan');
insert into posta (postna_st, posta) values (269, 'Podstepki');
insert into posta (postna_st, posta) values (270, 'Hepu');
insert into posta (postna_st, posta) values (271, 'Langchi');
insert into posta (postna_st, posta) values (272, 'Aguas Corrientes');
insert into posta (postna_st, posta) values (273, 'Manzanares');
insert into posta (postna_st, posta) values (274, 'Cimongkor');
insert into posta (postna_st, posta) values (275, 'Sindangbarang');
insert into posta (postna_st, posta) values (276, 'Caihua');
insert into posta (postna_st, posta) values (277, 'Gainesville');
insert into posta (postna_st, posta) values (278, 'Bloemfontein');
insert into posta (postna_st, posta) values (279, 'San Jose');
insert into posta (postna_st, posta) values (280, 'Chanuman');
insert into posta (postna_st, posta) values (281, 'Pindorama');
insert into posta (postna_st, posta) values (282, 'Colima');
insert into posta (postna_st, posta) values (283, 'Baturyn');
insert into posta (postna_st, posta) values (284, 'Zhukovskiy');
insert into posta (postna_st, posta) values (285, 'Coronel Vivida');
insert into posta (postna_st, posta) values (286, 'El Tambo');
insert into posta (postna_st, posta) values (287, 'Kibonsod');
insert into posta (postna_st, posta) values (288, 'Chigang');
insert into posta (postna_st, posta) values (289, 'Andou');
insert into posta (postna_st, posta) values (290, 'Duifang');
insert into posta (postna_st, posta) values (291, 'Malaga');
insert into posta (postna_st, posta) values (292, 'Chengfeng');
insert into posta (postna_st, posta) values (293, 'Kota Kinabalu');
insert into posta (postna_st, posta) values (294, 'Jixing');
insert into posta (postna_st, posta) values (295, 'Jambuwerkrajan');
insert into posta (postna_st, posta) values (296, 'Malé Svatoňovice');
insert into posta (postna_st, posta) values (297, 'Agua Blanca');
insert into posta (postna_st, posta) values (298, 'Lelkowo');
insert into posta (postna_st, posta) values (299, 'Sanqiao');
insert into posta (postna_st, posta) values (300, 'Wujiabao');
insert into posta (postna_st, posta) values (301, 'Saint-Paul');
insert into posta (postna_st, posta) values (302, 'Penebel');
insert into posta (postna_st, posta) values (303, 'Kaltan');
insert into posta (postna_st, posta) values (304, 'Wuyang');
insert into posta (postna_st, posta) values (305, 'Solsona');
insert into posta (postna_st, posta) values (306, 'Velykyy Klyuchiv');
insert into posta (postna_st, posta) values (307, 'Shin’ichi');
insert into posta (postna_st, posta) values (308, 'Yasenevo');
insert into posta (postna_st, posta) values (309, 'Tilmi');
insert into posta (postna_st, posta) values (310, 'Ust’-Isha');
insert into posta (postna_st, posta) values (311, 'Kamen');
insert into posta (postna_st, posta) values (312, 'Badajoz');
insert into posta (postna_st, posta) values (313, 'Banjar Delodrurung');
insert into posta (postna_st, posta) values (314, 'Jacksonville');
insert into posta (postna_st, posta) values (315, 'Danbury');
insert into posta (postna_st, posta) values (316, 'El Plan');
insert into posta (postna_st, posta) values (317, 'Baishui');
insert into posta (postna_st, posta) values (318, 'Trelleborg');
insert into posta (postna_st, posta) values (319, 'Permas');
insert into posta (postna_st, posta) values (320, 'Xincheng');
insert into posta (postna_st, posta) values (321, 'Bacabal');
insert into posta (postna_st, posta) values (322, 'Akhtarīn');
insert into posta (postna_st, posta) values (323, 'Cisalakdesa');
insert into posta (postna_st, posta) values (324, 'Yanghou');
insert into posta (postna_st, posta) values (325, 'Luoqi');
insert into posta (postna_st, posta) values (326, 'Shchigry');
insert into posta (postna_st, posta) values (327, 'Las Tunas');
insert into posta (postna_st, posta) values (328, 'Lunel');
insert into posta (postna_st, posta) values (329, 'Swan Hills');
insert into posta (postna_st, posta) values (330, 'Tanjung');
insert into posta (postna_st, posta) values (331, 'Fosses');
insert into posta (postna_st, posta) values (332, 'Marsabit');
insert into posta (postna_st, posta) values (333, 'Mbocayaty');
insert into posta (postna_st, posta) values (334, 'Esigodini');
insert into posta (postna_st, posta) values (335, 'Ningtang');
insert into posta (postna_st, posta) values (336, 'Fartura');
insert into posta (postna_st, posta) values (337, 'Bang Len');
insert into posta (postna_st, posta) values (338, 'La Paz');
insert into posta (postna_st, posta) values (339, 'Šenkovec');
insert into posta (postna_st, posta) values (340, 'Louisville');
insert into posta (postna_st, posta) values (341, 'Huangyang');
insert into posta (postna_st, posta) values (342, 'Araripina');
insert into posta (postna_st, posta) values (343, 'Bořitov');
insert into posta (postna_st, posta) values (344, 'Peremyshl’');
insert into posta (postna_st, posta) values (345, 'Quanshang');
insert into posta (postna_st, posta) values (346, 'Biruinţa');
insert into posta (postna_st, posta) values (347, 'Swift Current');
insert into posta (postna_st, posta) values (348, 'Ostrožská Nová Ves');
insert into posta (postna_st, posta) values (349, 'Jiqu');
insert into posta (postna_st, posta) values (350, 'Wyszki');
insert into posta (postna_st, posta) values (351, 'Miratejo');
insert into posta (postna_st, posta) values (352, '5 de Mayo');
insert into posta (postna_st, posta) values (353, 'Basel');
insert into posta (postna_st, posta) values (354, 'San Isidro');
insert into posta (postna_st, posta) values (355, 'Huzhen');
insert into posta (postna_st, posta) values (356, 'Vila Nova de Santo André');
insert into posta (postna_st, posta) values (357, 'Kaka');
insert into posta (postna_st, posta) values (358, 'Herálec');
insert into posta (postna_st, posta) values (359, 'Besteiros');
insert into posta (postna_st, posta) values (360, 'Boco');
insert into posta (postna_st, posta) values (361, 'Taipingzhuang');
insert into posta (postna_st, posta) values (362, 'Biljača');
insert into posta (postna_st, posta) values (363, 'Yanwo');
insert into posta (postna_st, posta) values (364, 'Périgny');
insert into posta (postna_st, posta) values (365, 'Madīnat Lab‘ūs');
insert into posta (postna_st, posta) values (366, 'Al Badārī');
insert into posta (postna_st, posta) values (367, 'Labuan');
insert into posta (postna_st, posta) values (368, 'Mazra‘at Bayt Jinn');
insert into posta (postna_st, posta) values (369, 'Lingbei');
insert into posta (postna_st, posta) values (370, 'Santa Cruz');
insert into posta (postna_st, posta) values (371, 'Ubatã');
insert into posta (postna_st, posta) values (372, 'Nantes');
insert into posta (postna_st, posta) values (373, 'San Rafael');
insert into posta (postna_st, posta) values (374, 'Oslo');
insert into posta (postna_st, posta) values (375, 'Matumadua');
insert into posta (postna_st, posta) values (376, 'Smołdzino');
insert into posta (postna_st, posta) values (377, 'Nelipyno');
insert into posta (postna_st, posta) values (378, 'Nakhon Phanom');
insert into posta (postna_st, posta) values (379, 'Independencia');
insert into posta (postna_st, posta) values (380, 'Hongchang');
insert into posta (postna_st, posta) values (381, 'Gucheng');
insert into posta (postna_st, posta) values (382, 'Tatebal');
insert into posta (postna_st, posta) values (383, 'Motema');
insert into posta (postna_st, posta) values (384, 'Vera Cruz');
insert into posta (postna_st, posta) values (385, 'Amberd');
insert into posta (postna_st, posta) values (386, 'Krajan');
insert into posta (postna_st, posta) values (387, 'Bang Sai');
insert into posta (postna_st, posta) values (388, 'Jiangshan');
insert into posta (postna_st, posta) values (389, 'Tielong');
insert into posta (postna_st, posta) values (390, 'Sumbersarikrajan');
insert into posta (postna_st, posta) values (391, 'Surubim');
insert into posta (postna_st, posta) values (392, 'Tamontaka');
insert into posta (postna_st, posta) values (393, 'Shigou');
insert into posta (postna_st, posta) values (394, 'Talisayan');
insert into posta (postna_st, posta) values (395, 'Menzel Abderhaman');
insert into posta (postna_st, posta) values (396, 'Udon Thani');
insert into posta (postna_st, posta) values (397, 'Carabayllo');
insert into posta (postna_st, posta) values (398, 'El Carmen');
insert into posta (postna_st, posta) values (399, 'Topol’noye');
insert into posta (postna_st, posta) values (400, 'Espargos');
insert into posta (postna_st, posta) values (401, 'Memphis');
insert into posta (postna_st, posta) values (402, 'Mazkeret Batya');
insert into posta (postna_st, posta) values (403, 'Wushi');
insert into posta (postna_st, posta) values (404, 'Canavieiras');
insert into posta (postna_st, posta) values (405, 'Pelileo');
insert into posta (postna_st, posta) values (406, 'Ordzhonikidzevskiy');
insert into posta (postna_st, posta) values (407, 'Pongol');
insert into posta (postna_st, posta) values (408, 'Guacarí');
insert into posta (postna_st, posta) values (409, 'Pajaten');
insert into posta (postna_st, posta) values (410, 'San Francisco de Yare');
insert into posta (postna_st, posta) values (411, 'Najd al Jumā‘ī');
insert into posta (postna_st, posta) values (412, 'Suka Makmue');
insert into posta (postna_st, posta) values (413, 'Essang');
insert into posta (postna_st, posta) values (414, 'Chester');
insert into posta (postna_st, posta) values (415, 'Kafr az Zayyāt');
insert into posta (postna_st, posta) values (416, 'Las Vegas');
insert into posta (postna_st, posta) values (417, 'Pimenta Bueno');
insert into posta (postna_st, posta) values (418, 'Kandangsapi');
insert into posta (postna_st, posta) values (419, 'San Nicolas');
insert into posta (postna_st, posta) values (420, 'Vällingby');
insert into posta (postna_st, posta) values (421, 'Sujiatuo');
insert into posta (postna_st, posta) values (422, 'Krutaya Gorka');
insert into posta (postna_st, posta) values (423, 'Xiangzikou');
insert into posta (postna_st, posta) values (424, 'Huangshi');
insert into posta (postna_st, posta) values (425, 'Fovissste');
insert into posta (postna_st, posta) values (426, 'Girona');
insert into posta (postna_st, posta) values (427, 'Sergokala');
insert into posta (postna_st, posta) values (428, 'Rungis');
insert into posta (postna_st, posta) values (429, 'Ndwedwe');
insert into posta (postna_st, posta) values (430, 'Kiambu');
insert into posta (postna_st, posta) values (431, 'Weiyuan');
insert into posta (postna_st, posta) values (432, 'Caen');
insert into posta (postna_st, posta) values (433, 'Leiden');
insert into posta (postna_st, posta) values (434, 'Jagabaya Dua');
insert into posta (postna_st, posta) values (435, 'Mayo');
insert into posta (postna_st, posta) values (436, 'Guayabal');
insert into posta (postna_st, posta) values (437, 'Lingkou');
insert into posta (postna_st, posta) values (438, 'Amuñgan');
insert into posta (postna_st, posta) values (439, 'Kondrovo');
insert into posta (postna_st, posta) values (440, 'Nossa Senhora da Glória');
insert into posta (postna_st, posta) values (441, 'Yuping');
insert into posta (postna_st, posta) values (442, 'Norsborg');
insert into posta (postna_st, posta) values (443, 'Sandakan');
insert into posta (postna_st, posta) values (444, 'Şabrātah');
insert into posta (postna_st, posta) values (445, 'Fuzhiping');
insert into posta (postna_st, posta) values (446, 'Sartana');
insert into posta (postna_st, posta) values (447, 'Wa’erma');
insert into posta (postna_st, posta) values (448, 'Jingyang');
insert into posta (postna_st, posta) values (449, 'Davao');
insert into posta (postna_st, posta) values (450, 'Sanjiangkou');
insert into posta (postna_st, posta) values (451, 'Montgomery');
insert into posta (postna_st, posta) values (452, 'Santa Monica');
insert into posta (postna_st, posta) values (453, 'Guacarí');
insert into posta (postna_st, posta) values (454, 'Presa');
insert into posta (postna_st, posta) values (455, 'Mamboma');
insert into posta (postna_st, posta) values (456, 'Konice');
insert into posta (postna_st, posta) values (457, 'Houping');
insert into posta (postna_st, posta) values (458, 'Américo Brasiliense');
insert into posta (postna_st, posta) values (459, 'El Estor');
insert into posta (postna_st, posta) values (460, 'Lixin');
insert into posta (postna_st, posta) values (461, 'Silihe');
insert into posta (postna_st, posta) values (462, 'Marihatag');
insert into posta (postna_st, posta) values (463, 'Campo Belo');
insert into posta (postna_st, posta) values (464, 'Si Thep');
insert into posta (postna_st, posta) values (465, 'Klau');
insert into posta (postna_st, posta) values (466, 'Xilópolis');
insert into posta (postna_st, posta) values (467, 'Samut Sakhon');
insert into posta (postna_st, posta) values (468, 'Taiyang');
insert into posta (postna_st, posta) values (469, 'Mingjiu');
insert into posta (postna_st, posta) values (470, 'Yarabamba');
insert into posta (postna_st, posta) values (471, 'Xialiao');
insert into posta (postna_st, posta) values (472, 'Akkol’');
insert into posta (postna_st, posta) values (473, 'Saryg-Sep');
insert into posta (postna_st, posta) values (474, 'Kosmonosy');
insert into posta (postna_st, posta) values (475, 'Wugong');
insert into posta (postna_st, posta) values (476, 'Tanay');
insert into posta (postna_st, posta) values (477, 'Dinskaya');
insert into posta (postna_st, posta) values (478, 'Apurawan');
insert into posta (postna_st, posta) values (479, 'Taimaman');
insert into posta (postna_st, posta) values (480, 'Žalec');
insert into posta (postna_st, posta) values (481, 'Quinta da Torre');
insert into posta (postna_st, posta) values (482, 'Sumbersewu');
insert into posta (postna_st, posta) values (483, 'Aimin');
insert into posta (postna_st, posta) values (484, 'Laborde');
insert into posta (postna_st, posta) values (485, 'Thị Trấn Mộc Châu');
insert into posta (postna_st, posta) values (486, 'Patea');
insert into posta (postna_st, posta) values (487, 'Dongxi');
insert into posta (postna_st, posta) values (488, 'Santa Luċija');
insert into posta (postna_st, posta) values (489, 'Xinlin');
insert into posta (postna_st, posta) values (490, 'Javorník');
insert into posta (postna_st, posta) values (491, 'Igarra');
insert into posta (postna_st, posta) values (492, 'Langgen');
insert into posta (postna_st, posta) values (493, 'Quintas');
insert into posta (postna_st, posta) values (494, 'Buyant');
insert into posta (postna_st, posta) values (495, 'Santa Elena');
insert into posta (postna_st, posta) values (496, 'Elaiochóri');
insert into posta (postna_st, posta) values (497, 'Ballsh');
insert into posta (postna_st, posta) values (498, 'Limoges');
insert into posta (postna_st, posta) values (499, 'Sampaloc');
insert into posta (postna_st, posta) values (500, 'Ambulong');
insert into posta (postna_st, posta) values (501, 'Stronie');
insert into posta (postna_st, posta) values (502, 'San Sebastian');
insert into posta (postna_st, posta) values (503, 'Latacunga');
insert into posta (postna_st, posta) values (504, 'Bagumbayan');
insert into posta (postna_st, posta) values (505, 'Burao');
insert into posta (postna_st, posta) values (506, 'Haibara');
insert into posta (postna_st, posta) values (507, 'Mukacheve');
insert into posta (postna_st, posta) values (508, 'Anxi');
insert into posta (postna_st, posta) values (509, 'Chatou');
insert into posta (postna_st, posta) values (510, 'Cirumput');
insert into posta (postna_st, posta) values (511, 'Peñal');
insert into posta (postna_st, posta) values (512, 'Xiabao');
insert into posta (postna_st, posta) values (513, 'Rantaupanjang');
insert into posta (postna_st, posta) values (514, 'Shilu');
insert into posta (postna_st, posta) values (515, 'Guimarães');
insert into posta (postna_st, posta) values (516, 'Sevaster');
insert into posta (postna_st, posta) values (517, 'Kil’mez’');
insert into posta (postna_st, posta) values (518, 'Abū Mūsā');
insert into posta (postna_st, posta) values (519, 'Nickby');
insert into posta (postna_st, posta) values (520, 'Åstorp');
insert into posta (postna_st, posta) values (521, 'Si Somdet');
insert into posta (postna_st, posta) values (522, 'Houzhen');
insert into posta (postna_st, posta) values (523, 'Granja');
insert into posta (postna_st, posta) values (524, 'Ljusdal');
insert into posta (postna_st, posta) values (525, 'Río');
insert into posta (postna_st, posta) values (526, 'Chrysoúpolis');
insert into posta (postna_st, posta) values (527, 'Guisser');
insert into posta (postna_st, posta) values (528, 'Novokhovrino');
insert into posta (postna_st, posta) values (529, 'Votuporanga');
insert into posta (postna_st, posta) values (530, 'Sicaya');
insert into posta (postna_st, posta) values (531, 'Mehendiganj');
insert into posta (postna_st, posta) values (532, 'Mongu');
insert into posta (postna_st, posta) values (533, 'Montargis');
insert into posta (postna_st, posta) values (534, 'Puyang');
insert into posta (postna_st, posta) values (535, 'Lisewo Malborskie');
insert into posta (postna_st, posta) values (536, 'Sơn Tây');
insert into posta (postna_st, posta) values (537, 'Qarah Bāgh');
insert into posta (postna_st, posta) values (538, 'Benhao');
insert into posta (postna_st, posta) values (539, 'Shuibian');
insert into posta (postna_st, posta) values (540, 'Orlovo');
insert into posta (postna_st, posta) values (541, 'Trondheim');
insert into posta (postna_st, posta) values (542, 'Jindong');
insert into posta (postna_st, posta) values (543, 'Dusun Tengah Cihaurbeuti');
insert into posta (postna_st, posta) values (544, 'Łeba');
insert into posta (postna_st, posta) values (545, 'Rydzyna');
insert into posta (postna_st, posta) values (546, 'Gardēz');
insert into posta (postna_st, posta) values (547, 'Rozkishne');
insert into posta (postna_st, posta) values (548, 'Semey');
insert into posta (postna_st, posta) values (549, 'Maukaro');
insert into posta (postna_st, posta) values (550, 'Quimper');
insert into posta (postna_st, posta) values (551, 'Liufang');
insert into posta (postna_st, posta) values (552, 'Sanxi');
insert into posta (postna_st, posta) values (553, 'Hienghène');
insert into posta (postna_st, posta) values (554, 'Ratchasan');
insert into posta (postna_st, posta) values (555, 'Andaray');
insert into posta (postna_st, posta) values (556, 'Singasari');
insert into posta (postna_st, posta) values (557, 'Krasnaya Polyana');
insert into posta (postna_st, posta) values (558, 'Wuquan');
insert into posta (postna_st, posta) values (559, 'Montijo');
insert into posta (postna_st, posta) values (560, 'Sibay');
insert into posta (postna_st, posta) values (561, 'Colonia Elisa');
insert into posta (postna_st, posta) values (562, 'Kruševo');
insert into posta (postna_st, posta) values (563, 'Phayakkhaphum Phisai');
insert into posta (postna_st, posta) values (564, 'Pozuzo');
insert into posta (postna_st, posta) values (565, 'Chuandao');
insert into posta (postna_st, posta) values (566, 'Dongmaku');
insert into posta (postna_st, posta) values (567, 'Djohong');
insert into posta (postna_st, posta) values (568, 'Kajisara');
insert into posta (postna_st, posta) values (569, 'Yirga ‘Alem');
insert into posta (postna_st, posta) values (570, 'Verblyany');
insert into posta (postna_st, posta) values (571, 'Saint Louis');
insert into posta (postna_st, posta) values (572, 'Juanshui');
insert into posta (postna_st, posta) values (573, 'Zvezdara');
insert into posta (postna_st, posta) values (574, 'Líbeznice');
insert into posta (postna_st, posta) values (575, 'Sredniy');
insert into posta (postna_st, posta) values (576, 'Butterworth');
insert into posta (postna_st, posta) values (577, 'Xicun');
insert into posta (postna_st, posta) values (578, 'Liulin');
insert into posta (postna_st, posta) values (579, 'Přibyslav');
insert into posta (postna_st, posta) values (580, 'Kool Tengah');
insert into posta (postna_st, posta) values (581, 'Talangnan');
insert into posta (postna_st, posta) values (582, 'Shangyi');
insert into posta (postna_st, posta) values (583, 'Caohezhang');
insert into posta (postna_st, posta) values (584, 'Guinobatan');
insert into posta (postna_st, posta) values (585, 'Ciechocin');
insert into posta (postna_st, posta) values (586, 'Wadi');
insert into posta (postna_st, posta) values (587, 'Jaroměřice');
insert into posta (postna_st, posta) values (588, 'Ledok');
insert into posta (postna_st, posta) values (589, 'Bhamdoûn el Mhatta');
insert into posta (postna_st, posta) values (590, 'Nikol’skoye');
insert into posta (postna_st, posta) values (591, 'Nanbin');
insert into posta (postna_st, posta) values (592, 'Oslo');
insert into posta (postna_st, posta) values (593, 'Goričan');
insert into posta (postna_st, posta) values (594, 'Tong’an');
insert into posta (postna_st, posta) values (595, 'Haveli');
insert into posta (postna_st, posta) values (596, 'Kondoa');
insert into posta (postna_st, posta) values (597, 'Guishan');
insert into posta (postna_st, posta) values (598, 'Vilca');
insert into posta (postna_st, posta) values (599, 'Artemisa');
insert into posta (postna_st, posta) values (600, 'Mstsislaw');
insert into posta (postna_st, posta) values (601, 'Mapiripán');
insert into posta (postna_st, posta) values (602, 'Hanggan');
insert into posta (postna_st, posta) values (603, 'Krajan Keboromo');
insert into posta (postna_st, posta) values (604, 'Hässelby');
insert into posta (postna_st, posta) values (605, 'Nice');
insert into posta (postna_st, posta) values (606, 'Kabasalan');
insert into posta (postna_st, posta) values (607, 'Chum Phuang');
insert into posta (postna_st, posta) values (608, 'Manique de Baixo');
insert into posta (postna_st, posta) values (609, 'Bai’e');
insert into posta (postna_st, posta) values (610, 'Honglan');
insert into posta (postna_st, posta) values (611, 'Orlando');
insert into posta (postna_st, posta) values (612, 'Enewetak');
insert into posta (postna_st, posta) values (613, 'Nanguzhuang');
insert into posta (postna_st, posta) values (614, 'Partesh');
insert into posta (postna_st, posta) values (615, 'Áyios Vasílios');
insert into posta (postna_st, posta) values (616, 'Sishui');
insert into posta (postna_st, posta) values (617, 'Godong');
insert into posta (postna_st, posta) values (618, 'Saint-Jean-de-Monts');
insert into posta (postna_st, posta) values (619, 'Xiayunling');
insert into posta (postna_st, posta) values (620, 'Xinning');
insert into posta (postna_st, posta) values (621, 'Lirang');
insert into posta (postna_st, posta) values (622, 'Benito Juarez');
insert into posta (postna_st, posta) values (623, 'Desa Wetan Ciakar');
insert into posta (postna_st, posta) values (624, 'Radomir');
insert into posta (postna_st, posta) values (625, 'Dahe');
insert into posta (postna_st, posta) values (626, 'Cruz');
insert into posta (postna_st, posta) values (627, 'Moguqi');
insert into posta (postna_st, posta) values (628, 'Bang Krathum');
insert into posta (postna_st, posta) values (629, 'Dahuang');
insert into posta (postna_st, posta) values (630, 'Verkh-Usugli');
insert into posta (postna_st, posta) values (631, 'Xinqiao');
insert into posta (postna_st, posta) values (632, 'Armavir');
insert into posta (postna_st, posta) values (633, 'Devin');
insert into posta (postna_st, posta) values (634, 'Sa''dah');
insert into posta (postna_st, posta) values (635, 'Moriki');
insert into posta (postna_st, posta) values (636, 'Marapanim');
insert into posta (postna_st, posta) values (637, 'Liucheng');
insert into posta (postna_st, posta) values (638, 'Loshnitsa');
insert into posta (postna_st, posta) values (639, 'Itigi');
insert into posta (postna_st, posta) values (640, 'Sirte');
insert into posta (postna_st, posta) values (641, 'Singasari');
insert into posta (postna_st, posta) values (642, 'Qingliu');
insert into posta (postna_st, posta) values (643, 'Enköping');
insert into posta (postna_st, posta) values (644, 'Maskinongé');
insert into posta (postna_st, posta) values (645, 'Kamru');
insert into posta (postna_st, posta) values (646, 'Dobruševo');
insert into posta (postna_st, posta) values (647, 'Deder');
insert into posta (postna_st, posta) values (648, 'Vale');
insert into posta (postna_st, posta) values (649, 'Santa Rosa');
insert into posta (postna_st, posta) values (650, 'Serowe');
insert into posta (postna_st, posta) values (651, 'Shuanglongchang');
insert into posta (postna_st, posta) values (652, 'Guluoshan');
insert into posta (postna_st, posta) values (653, 'Gorzyce');
insert into posta (postna_st, posta) values (654, 'Arcoverde');
insert into posta (postna_st, posta) values (655, 'Pangian');
insert into posta (postna_st, posta) values (656, 'Sietesz');
insert into posta (postna_st, posta) values (657, 'Dagua');
insert into posta (postna_st, posta) values (658, 'Rueil-Malmaison');
insert into posta (postna_st, posta) values (659, 'Florida');
insert into posta (postna_st, posta) values (660, 'Malo');
insert into posta (postna_st, posta) values (661, 'Sŏnbong');
insert into posta (postna_st, posta) values (662, 'Alameda');
insert into posta (postna_st, posta) values (663, 'Tanjung Kidul');
insert into posta (postna_st, posta) values (664, 'Zhanghuban');
insert into posta (postna_st, posta) values (665, 'Edineţ');
insert into posta (postna_st, posta) values (666, 'Xintian');
insert into posta (postna_st, posta) values (667, 'Néa Ionía');
insert into posta (postna_st, posta) values (668, 'Xinhua');
insert into posta (postna_st, posta) values (669, 'Kolambugan');
insert into posta (postna_st, posta) values (670, 'Węgrzce Wielkie');
insert into posta (postna_st, posta) values (671, 'Borlänge');
insert into posta (postna_st, posta) values (672, 'Somdet');
insert into posta (postna_st, posta) values (673, 'Fukuoka-shi');
insert into posta (postna_st, posta) values (674, 'Zhentou');
insert into posta (postna_st, posta) values (675, 'Eṭ Ṭaiyiba');
insert into posta (postna_st, posta) values (676, 'Checca');
insert into posta (postna_st, posta) values (677, 'Acatenango');
insert into posta (postna_st, posta) values (678, 'Saint-Raymond');
insert into posta (postna_st, posta) values (679, 'Guanay');
insert into posta (postna_st, posta) values (680, 'Ibaan');
insert into posta (postna_st, posta) values (681, 'Veruela');
insert into posta (postna_st, posta) values (682, 'Springfield');
insert into posta (postna_st, posta) values (683, 'Paratinga');
insert into posta (postna_st, posta) values (684, 'Zyuzino');
insert into posta (postna_st, posta) values (685, 'Pilawa');
insert into posta (postna_st, posta) values (686, 'Kaburon');
insert into posta (postna_st, posta) values (687, 'Roliça');
insert into posta (postna_st, posta) values (688, 'Ciguna');
insert into posta (postna_st, posta) values (689, 'Colorado Springs');
insert into posta (postna_st, posta) values (690, 'Dawusu');
insert into posta (postna_st, posta) values (691, 'El Tambo');
insert into posta (postna_st, posta) values (692, 'Ngudu');
insert into posta (postna_st, posta) values (693, 'Kushk');
insert into posta (postna_st, posta) values (694, 'Kabarnet');
insert into posta (postna_st, posta) values (695, 'Cikaso');
insert into posta (postna_st, posta) values (696, 'Krajan Timur Suger Kidul');
insert into posta (postna_st, posta) values (697, 'Zavolzh’ye');
insert into posta (postna_st, posta) values (698, 'Hongguang');
insert into posta (postna_st, posta) values (699, 'Nukuoro');
insert into posta (postna_st, posta) values (700, 'New York City');
insert into posta (postna_st, posta) values (701, 'Datong');
insert into posta (postna_st, posta) values (702, 'Monastir');
insert into posta (postna_st, posta) values (703, 'Veiga');
insert into posta (postna_st, posta) values (704, 'Outing');
insert into posta (postna_st, posta) values (705, 'Novosil’');
insert into posta (postna_st, posta) values (706, 'Kariya');
insert into posta (postna_st, posta) values (707, 'Laḩij');
insert into posta (postna_st, posta) values (708, 'Guandu');
insert into posta (postna_st, posta) values (709, 'Jengglungharjo');
insert into posta (postna_st, posta) values (710, 'Barreira');
insert into posta (postna_st, posta) values (711, 'Rancharia');
insert into posta (postna_st, posta) values (712, 'Prilep');
insert into posta (postna_st, posta) values (713, 'Goussainville');
insert into posta (postna_st, posta) values (714, 'Sandao');
insert into posta (postna_st, posta) values (715, 'Mojogajeh');
insert into posta (postna_st, posta) values (716, 'Västerås');
insert into posta (postna_st, posta) values (717, 'Jobabo');
insert into posta (postna_st, posta) values (718, 'Pakel');
insert into posta (postna_st, posta) values (719, 'Zemio');
insert into posta (postna_st, posta) values (720, 'Birātnagar');
insert into posta (postna_st, posta) values (721, 'Katy');
insert into posta (postna_st, posta) values (722, 'Stubno');
insert into posta (postna_st, posta) values (723, 'Viamão');
insert into posta (postna_st, posta) values (724, 'Hongqi');
insert into posta (postna_st, posta) values (725, 'São Bento');
insert into posta (postna_st, posta) values (726, 'Chorotis');
insert into posta (postna_st, posta) values (727, 'Voyutychi');
insert into posta (postna_st, posta) values (728, 'Yonkers');
insert into posta (postna_st, posta) values (729, 'Nakhodka');
insert into posta (postna_st, posta) values (730, 'Krylovskaya');
insert into posta (postna_st, posta) values (731, 'San Jose');
insert into posta (postna_st, posta) values (732, 'Progreso');
insert into posta (postna_st, posta) values (733, 'Gangba');
insert into posta (postna_st, posta) values (734, 'Al ‘Anān');
insert into posta (postna_st, posta) values (735, 'Cabinteely');
insert into posta (postna_st, posta) values (736, 'Mojomulyokrajan');
insert into posta (postna_st, posta) values (737, 'Kabar Utara');
insert into posta (postna_st, posta) values (738, 'Göteborg');
insert into posta (postna_st, posta) values (739, 'Zalantun');
insert into posta (postna_st, posta) values (740, 'Bilar');
insert into posta (postna_st, posta) values (741, 'Kuala Lumpur');
insert into posta (postna_st, posta) values (742, 'Saint Louis');
insert into posta (postna_st, posta) values (743, 'Shanjiao');
insert into posta (postna_st, posta) values (744, 'Tours');
insert into posta (postna_st, posta) values (745, 'Árta');
insert into posta (postna_st, posta) values (746, 'Penha');
insert into posta (postna_st, posta) values (747, 'Urengoy');
insert into posta (postna_st, posta) values (748, 'Alès');
insert into posta (postna_st, posta) values (749, 'Goz Beïda');
insert into posta (postna_st, posta) values (750, 'São Miguel do Iguaçu');
insert into posta (postna_st, posta) values (751, 'Yitulihe');
insert into posta (postna_st, posta) values (752, 'Novosheshminsk');
insert into posta (postna_st, posta) values (753, 'Čajetina');
insert into posta (postna_st, posta) values (754, 'Rūdiškės');
insert into posta (postna_st, posta) values (755, 'Banjar Sedang');
insert into posta (postna_st, posta) values (756, 'Argungu');
insert into posta (postna_st, posta) values (757, 'Liuzikou');
insert into posta (postna_st, posta) values (758, 'Stepove');
insert into posta (postna_st, posta) values (759, 'Rezovac');
insert into posta (postna_st, posta) values (760, 'Jiamaogong');
insert into posta (postna_st, posta) values (761, 'Utrecht (stad)');
insert into posta (postna_st, posta) values (762, 'Kashima-shi');
insert into posta (postna_st, posta) values (763, 'Changmaoling');
insert into posta (postna_st, posta) values (764, 'Amagi');
insert into posta (postna_st, posta) values (765, 'Fresno');
insert into posta (postna_st, posta) values (766, 'Ampelgading');
insert into posta (postna_st, posta) values (767, 'Minna');
insert into posta (postna_st, posta) values (768, 'Miguel Hidalgo');
insert into posta (postna_st, posta) values (769, 'El Fasher');
insert into posta (postna_st, posta) values (770, 'Yoshkar-Ola');
insert into posta (postna_st, posta) values (771, 'Tsibulev');
insert into posta (postna_st, posta) values (772, 'Ngorongoro');
insert into posta (postna_st, posta) values (773, 'Dailing');
insert into posta (postna_st, posta) values (774, 'Xijiang');
insert into posta (postna_st, posta) values (775, 'Umeå');
insert into posta (postna_st, posta) values (776, 'Ängelholm');
insert into posta (postna_st, posta) values (777, 'Xiangang');
insert into posta (postna_st, posta) values (778, 'Koynare');
insert into posta (postna_st, posta) values (779, 'Wudian');
insert into posta (postna_st, posta) values (780, 'Pacanga');
insert into posta (postna_st, posta) values (781, 'Brisbane');
insert into posta (postna_st, posta) values (782, 'Foxrock');
insert into posta (postna_st, posta) values (783, 'Cowansville');
insert into posta (postna_st, posta) values (784, 'Lughaye');
insert into posta (postna_st, posta) values (785, 'Curahuasi');
insert into posta (postna_st, posta) values (786, 'Panalanoy');
insert into posta (postna_st, posta) values (787, 'Honghualiangzi');
insert into posta (postna_st, posta) values (788, 'Mont-de-Marsan');
insert into posta (postna_st, posta) values (789, 'Akunk’');
insert into posta (postna_st, posta) values (790, 'Tuapukan');
insert into posta (postna_st, posta) values (791, 'Port Area');
insert into posta (postna_st, posta) values (792, 'Rušanj');
insert into posta (postna_st, posta) values (793, 'Kadoma');
insert into posta (postna_st, posta) values (794, 'Villa Paula de Sarmiento');
insert into posta (postna_st, posta) values (795, 'Fontana');
insert into posta (postna_st, posta) values (796, 'Nishio');
insert into posta (postna_st, posta) values (797, 'Shashemenē');
insert into posta (postna_st, posta) values (798, 'Neuville');
insert into posta (postna_st, posta) values (799, 'Paleran');
insert into posta (postna_st, posta) values (800, 'Zhongshu');
insert into posta (postna_st, posta) values (801, 'Kebonsari Kidul');
insert into posta (postna_st, posta) values (802, 'Alkmaar');
insert into posta (postna_st, posta) values (803, 'Presidente Médici');
insert into posta (postna_st, posta) values (804, 'Miguel Hidalgo');
insert into posta (postna_st, posta) values (805, 'Ḩarīb');
insert into posta (postna_st, posta) values (806, 'Lleida');
insert into posta (postna_st, posta) values (807, 'Kambia');
insert into posta (postna_st, posta) values (808, 'Qiankou');
insert into posta (postna_st, posta) values (809, 'Veternik');
insert into posta (postna_st, posta) values (810, 'Lấp Vò');
insert into posta (postna_st, posta) values (811, 'Pruchnik');
insert into posta (postna_st, posta) values (812, 'Shuangzhu');
insert into posta (postna_st, posta) values (813, 'Hengling');
insert into posta (postna_st, posta) values (814, 'Concepción');
insert into posta (postna_st, posta) values (815, 'Chambara');
insert into posta (postna_st, posta) values (816, 'Mazeikiai');
insert into posta (postna_st, posta) values (817, 'Taphan Hin');
insert into posta (postna_st, posta) values (818, 'Shuangzhong');
insert into posta (postna_st, posta) values (819, 'Ýdra');
insert into posta (postna_st, posta) values (820, 'Mazeikiai');
insert into posta (postna_st, posta) values (821, 'West Palm Beach');
insert into posta (postna_st, posta) values (822, 'Qianjia');
insert into posta (postna_st, posta) values (823, 'Mehar');
insert into posta (postna_st, posta) values (824, 'Svorónos');
insert into posta (postna_st, posta) values (825, 'Vyškov');
insert into posta (postna_st, posta) values (826, 'Sagana');
insert into posta (postna_st, posta) values (827, 'Dromiskin');
insert into posta (postna_st, posta) values (828, 'Ambositra');
insert into posta (postna_st, posta) values (829, 'Zhangjiayuan');
insert into posta (postna_st, posta) values (830, 'Kaliuling');
insert into posta (postna_st, posta) values (831, 'Yuanqiao');
insert into posta (postna_st, posta) values (832, 'Cotmon');
insert into posta (postna_st, posta) values (833, 'La Garenne-Colombes');
insert into posta (postna_st, posta) values (834, 'Novotroitsk');
insert into posta (postna_st, posta) values (835, 'Guanmiao');
insert into posta (postna_st, posta) values (836, 'Miyoshi');
insert into posta (postna_st, posta) values (837, 'Krasne');
insert into posta (postna_st, posta) values (838, 'Nagiba');
insert into posta (postna_st, posta) values (839, 'Oratorio');
insert into posta (postna_st, posta) values (840, 'Haninge');
insert into posta (postna_st, posta) values (841, 'Ratchasan');
insert into posta (postna_st, posta) values (842, 'Suncun');
insert into posta (postna_st, posta) values (843, 'Sadská');
insert into posta (postna_st, posta) values (844, 'Sunja');
insert into posta (postna_st, posta) values (845, 'Cangkuang');
insert into posta (postna_st, posta) values (846, 'Kowale Oleckie');
insert into posta (postna_st, posta) values (847, 'Thap Khlo');
insert into posta (postna_st, posta) values (848, 'Dolice');
insert into posta (postna_st, posta) values (849, 'Pekalongan');
insert into posta (postna_st, posta) values (850, 'Anguil');
insert into posta (postna_st, posta) values (851, 'Xuedian');
insert into posta (postna_st, posta) values (852, 'Storuman');
insert into posta (postna_st, posta) values (853, 'Jönköping');
insert into posta (postna_st, posta) values (854, 'Sukarama');
insert into posta (postna_st, posta) values (855, 'Kabare');
insert into posta (postna_st, posta) values (856, 'Rechitsy');
insert into posta (postna_st, posta) values (857, 'Pécs');
insert into posta (postna_st, posta) values (858, 'Ganhe');
insert into posta (postna_st, posta) values (859, 'Stockholm');
insert into posta (postna_st, posta) values (860, 'Tavricheskoye');
insert into posta (postna_st, posta) values (861, 'Iecava');
insert into posta (postna_st, posta) values (862, 'Cartago');
insert into posta (postna_st, posta) values (863, 'Sidareja');
insert into posta (postna_st, posta) values (864, 'Pechora');
insert into posta (postna_st, posta) values (865, 'Yingdianjie');
insert into posta (postna_st, posta) values (866, 'Sukmoilang');
insert into posta (postna_st, posta) values (867, 'Babakan Baru');
insert into posta (postna_st, posta) values (868, 'Colcabamba');
insert into posta (postna_st, posta) values (869, 'Huazhou');
insert into posta (postna_st, posta) values (870, 'Kostarea Satu');
insert into posta (postna_st, posta) values (871, 'Isperikh');
insert into posta (postna_st, posta) values (872, 'Furmanov');
insert into posta (postna_st, posta) values (873, 'Nuwaybi‘a');
insert into posta (postna_st, posta) values (874, '‘Ayn al Bayḑā');
insert into posta (postna_st, posta) values (875, 'Rongcheng');
insert into posta (postna_st, posta) values (876, 'Västerås');
insert into posta (postna_st, posta) values (877, 'Ribeirão das Neves');
insert into posta (postna_st, posta) values (878, 'Bagombong');
insert into posta (postna_st, posta) values (879, 'Al Qubbah');
insert into posta (postna_st, posta) values (880, 'Severskaya');
insert into posta (postna_st, posta) values (881, 'Jimaguayú');
insert into posta (postna_st, posta) values (882, 'Ḩātim');
insert into posta (postna_st, posta) values (883, 'Zea');
insert into posta (postna_st, posta) values (884, 'Chãos');
insert into posta (postna_st, posta) values (885, 'Lamam');
insert into posta (postna_st, posta) values (886, 'Bordeaux');
insert into posta (postna_st, posta) values (887, 'Ciudad Bolívar');
insert into posta (postna_st, posta) values (888, 'København');
insert into posta (postna_st, posta) values (889, 'Xuezhen');
insert into posta (postna_st, posta) values (890, 'Donggaocun');
insert into posta (postna_st, posta) values (891, 'Tây Hồ');
insert into posta (postna_st, posta) values (892, 'Yitang');
insert into posta (postna_st, posta) values (893, 'Guangyuan');
insert into posta (postna_st, posta) values (894, 'Jiangjia');
insert into posta (postna_st, posta) values (895, 'Guaramirim');
insert into posta (postna_st, posta) values (896, 'Itororó');
insert into posta (postna_st, posta) values (897, 'Wąwolnica');
insert into posta (postna_st, posta) values (898, 'San Buenaventura');
insert into posta (postna_st, posta) values (899, 'Mihara');
insert into posta (postna_st, posta) values (900, 'Maao');
insert into posta (postna_st, posta) values (901, 'Daweishan');
insert into posta (postna_st, posta) values (902, 'Al Ḩazm');
insert into posta (postna_st, posta) values (903, 'Shangqiu');
insert into posta (postna_st, posta) values (904, 'Purworejo');
insert into posta (postna_st, posta) values (905, 'Kidričevo');
insert into posta (postna_st, posta) values (906, 'Al Wajh');
insert into posta (postna_st, posta) values (907, 'Meziměstí');
insert into posta (postna_st, posta) values (908, 'Antanifotsy');
insert into posta (postna_st, posta) values (909, 'Xihu');
insert into posta (postna_st, posta) values (910, 'Lübeck');
insert into posta (postna_st, posta) values (911, 'Longtanping');
insert into posta (postna_st, posta) values (912, 'Zhen’an');
insert into posta (postna_st, posta) values (913, 'Dahua');
insert into posta (postna_st, posta) values (914, 'Thành Phố Lạng Sơn');
insert into posta (postna_st, posta) values (915, 'Daveluyville');
insert into posta (postna_st, posta) values (916, 'Libertad');
insert into posta (postna_st, posta) values (917, 'East End');
insert into posta (postna_st, posta) values (918, 'Cigaleuh Kulon');
insert into posta (postna_st, posta) values (919, 'Binawara');
insert into posta (postna_st, posta) values (920, 'Xiaosong');
insert into posta (postna_st, posta) values (921, 'Karangbenda');
insert into posta (postna_st, posta) values (922, 'Gujun');
insert into posta (postna_st, posta) values (923, 'Le Kremlin-Bicêtre');
insert into posta (postna_st, posta) values (924, 'Dong’an');
insert into posta (postna_st, posta) values (925, 'Las Matas de Santa Cruz');
insert into posta (postna_st, posta) values (926, 'Ransiki');
insert into posta (postna_st, posta) values (927, 'Huangfang');
insert into posta (postna_st, posta) values (928, 'Shreveport');
insert into posta (postna_st, posta) values (929, 'Cúa');
insert into posta (postna_st, posta) values (930, 'Solnechnogorsk');
insert into posta (postna_st, posta) values (931, 'Nurmijärvi');
insert into posta (postna_st, posta) values (932, 'Bulumulyo');
insert into posta (postna_st, posta) values (933, 'Bolotnoye');
insert into posta (postna_st, posta) values (934, 'Sitovo');
insert into posta (postna_st, posta) values (935, 'Gislaved');
insert into posta (postna_st, posta) values (936, 'Soweto');
insert into posta (postna_st, posta) values (937, 'Barra Mansa');
insert into posta (postna_st, posta) values (938, 'Tuanalepe');
insert into posta (postna_st, posta) values (939, 'Yueyang');
insert into posta (postna_st, posta) values (940, 'Trondheim');
insert into posta (postna_st, posta) values (941, 'Polańczyk');
insert into posta (postna_st, posta) values (942, 'Ngadipuro');
insert into posta (postna_st, posta) values (943, 'Comapa');
insert into posta (postna_st, posta) values (944, 'Paris 18');
insert into posta (postna_st, posta) values (945, 'Tournai');
insert into posta (postna_st, posta) values (946, 'Thị Trấn Ngọc Lặc');
insert into posta (postna_st, posta) values (947, 'Sukamaju');
insert into posta (postna_st, posta) values (948, 'Asadābād');
insert into posta (postna_st, posta) values (949, 'Izumi');
insert into posta (postna_st, posta) values (950, 'Iqaluit');
insert into posta (postna_st, posta) values (951, 'Nýřany');
insert into posta (postna_st, posta) values (952, 'Tai’an');
insert into posta (postna_st, posta) values (953, 'Lope de Vega');
insert into posta (postna_st, posta) values (954, 'Budenovetc');
insert into posta (postna_st, posta) values (955, 'Piancheng');
insert into posta (postna_st, posta) values (956, 'Vilkija');
insert into posta (postna_st, posta) values (957, 'Breda');
insert into posta (postna_st, posta) values (958, 'Komes');
insert into posta (postna_st, posta) values (959, 'Limeil-Brévannes');
insert into posta (postna_st, posta) values (960, 'Albacete');
insert into posta (postna_st, posta) values (961, 'Kirovskaya');
insert into posta (postna_st, posta) values (962, 'Terawas');
insert into posta (postna_st, posta) values (963, 'Gucheng');
insert into posta (postna_st, posta) values (964, 'Tam Bình');
insert into posta (postna_st, posta) values (965, 'Jesús María');
insert into posta (postna_st, posta) values (966, 'Ladan');
insert into posta (postna_st, posta) values (967, 'Skaryszew');
insert into posta (postna_st, posta) values (968, 'Pravdinsk');
insert into posta (postna_st, posta) values (969, 'Loacan');
insert into posta (postna_st, posta) values (970, 'Omuo-Ekiti');
insert into posta (postna_st, posta) values (971, 'Wa’erma');
insert into posta (postna_st, posta) values (972, 'Putrajawa');
insert into posta (postna_st, posta) values (973, 'Dalam');
insert into posta (postna_st, posta) values (974, 'Santa Cruz da Graciosa');
insert into posta (postna_st, posta) values (975, 'Changqing');
insert into posta (postna_st, posta) values (976, 'Linköping');
insert into posta (postna_st, posta) values (977, 'Santa Lucia');
insert into posta (postna_st, posta) values (978, 'Shouxihu');
insert into posta (postna_st, posta) values (979, 'Zouma');
insert into posta (postna_st, posta) values (980, 'Santa Cruz Balanyá');
insert into posta (postna_st, posta) values (981, 'Padangtikar');
insert into posta (postna_st, posta) values (982, 'La Guadalupe');
insert into posta (postna_st, posta) values (983, 'Valerianovsk');
insert into posta (postna_st, posta) values (984, 'Daixi');
insert into posta (postna_st, posta) values (985, 'Florencia');
insert into posta (postna_st, posta) values (986, 'El Quiteño');
insert into posta (postna_st, posta) values (987, 'Thorold');
insert into posta (postna_st, posta) values (988, 'Velika');
insert into posta (postna_st, posta) values (989, 'Ignalina');
insert into posta (postna_st, posta) values (990, 'Vinha');
insert into posta (postna_st, posta) values (991, 'Moscavide');
insert into posta (postna_st, posta) values (992, 'Kilifarevo');
insert into posta (postna_st, posta) values (993, 'Krasnyy Yar');
insert into posta (postna_st, posta) values (994, 'Alindao');
insert into posta (postna_st, posta) values (995, 'Bogra');
insert into posta (postna_st, posta) values (996, 'Utan');
insert into posta (postna_st, posta) values (997, 'Baolong');
insert into posta (postna_st, posta) values (998, 'Ambatolampy');
insert into posta (postna_st, posta) values (999, 'Yushugou');
insert into posta (postna_st, posta) values (1000, 'Qila Saifullāh');
